name: Build

on:
  push:
    branches:
      - master

jobs:
  sonarqube:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - - name: Build and analyze with Maven
          run: mvn clean verify sonar:sonar -DskipTests -Dsonar.host.url=https://sonarcloud.io
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
